# Generated by Django 4.0.6 on 2022-08-07 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_alter_groupchatroom_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='RoomName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupchatroom',
            name='members',
            field=models.ManyToManyField(related_name='groupmembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
