# Generated by Django 4.0.6 on 2022-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupchatroom_roomname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
