# Generated by Django 4.0.6 on 2022-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_personalchat_is_viewed_personalchatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchatroom',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='chats.personalchat'),
        ),
    ]
