# Generated by Django 4.0.6 on 2022-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_personalchatroom_roomname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchatroom',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalchatroom',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='chats.personalchat'),
        ),
    ]
