# Generated by Django 4.0.6 on 2022-08-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_personalchatroom_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalchatroom',
            name='group_id',
        ),
    ]
