# Generated by Django 4.0.6 on 2022-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_personalchatroom_members_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchatroom',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
