# Generated by Django 4.0.6 on 2022-08-07 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='groupmembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
